### ISSUE TITLE
Support for a Docker deployment

### ISSUE THREAD

**Issue by miltuss** [thefranke/rss-librarian#6]
There is currently no Docker image of rss-librarian. Please enable a Docker deployment of this wonderful tool.

**Comment by thefranke** [comment]
Unfortunately I have no knowledge of Docker. Do you expect the Docker image to just setup RSS-librarian, or install PHP and Apache itself together with RSS-Librarian and host it?

**Comment by miltuss** [comment]
I expect the docker image to contain all the dependencies needed to run RSS-Librarian (like php) and also RSS-Librarian itself. A bind volume could be programmed to sync the folder containing RSS-Librarian data outside the image for persistence, and configuring RSS-Librarian settings could be done from environment variables. Here's an example of what the RSS-Librarian Docker Compose file could look like:

```
version: "3.8"
services:
  dockge:
    image: docker.io/thefranke/rss-librarian:latest
    container_name: rss-librarian
    restart: always
    ports:
      - 8010:80
    volumes:
      - /path-host/data:/path-container/data
    environment:
      - FULL_TEXT_EXTRACTION: true
      - MAX_ITEMS_PER_FEED: 100 
```

**Comment by corvock** [comment]
That works for me .. there may be a better way, bnut it got where i wanted it. I have to supply the .php file into the config file and i let it create the config.json on first run then pulled that out of the container and mapped it back in so i can edit it outside 

```
---
services:
  nginx:
    image: lscr.io/linuxserver/nginx:latest
    container_name: rss-librarian-nginx
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - NGINX_AUTORELOAD= #optional
      - NGINX_AUTORELOAD_WATCHLIST= #optional
      - FULL_TEXT_EXTRACTION=true
      - MAX_ITEMS_PER_FEED=100         
    volumes:
      #- /path/to/nginx/config:/config
      - ./librarian.php:/config/www/index.php
      - ./rsslibrarian-config.json:/config/www/rsslibrarian-config.json      
      - ./feeds:/config/www/feeds
    ports:
      #- 8090:80
      - 8090:443
    restart: unless-stopped
```
